# Generated by Django 5.2.1 on 2025-06-03 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_profileview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileView',
        ),
    ]
